### ISSUE TITLE
Need help with Repositories

### ISSUE THREAD

**Issue by thehuze** [hakan-krgn/spigot-injection#17]
Hello. I'm trying to save an object to a database using your library. I looked at the example in the [full plugin](https://github.com/hakan-krgn/spigot-injection/tree/master/plugin-examples/full-plugin), there are no @Querу annotations for the save delete methods, etc. That's why I didn't add it to my test plugin. At the same time, I get an exception. Please take a look at the attachments below.

![image](https://github.com/hakan-krgn/spigot-injection/assets/49346608/ddf4b4f1-7d8a-4410-854d-fd1955cfc480)
![image](https://github.com/hakan-krgn/spigot-injection/assets/49346608/0c5826e3-3063-46fd-8116-e859c48c957d)
```
[16:51:24 ERROR]: Could not pass event BlockDestroyEvent to hibernate-test-for-spigot v1.0-SNAPSHOT
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.hakan.spinjection.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:47) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.utils.ReflectionUtils.runMethod(ReflectionUtils.java:69) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.listener.executor.ListenerExecutor.execute(ListenerExecutor.java:115) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2082]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.Level.destroyBlock(Level.java:1132) ~[?:?]
	at net.minecraft.world.level.block.Block.updateOrDestroy(Block.java:205) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.world.level.redstone.NeighborUpdater.executeShapeUpdate(NeighborUpdater.java:50) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater$ShapeUpdate.runNext(CollectingNeighborUpdater.java:158) ~[?:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.runUpdates(CollectingNeighborUpdater.java:79) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.addAndRun(CollectingNeighborUpdater.java:63) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.shapeUpdate(CollectingNeighborUpdater.java:30) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.world.level.Level.neighborShapeChanged(Level.java:1180) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.updateNeighbourShapes(BlockBehaviour.java:1183) ~[?:?]
	at net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:1095) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:1041) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:955) ~[?:?]
	at net.minecraft.world.level.Level.removeBlock(Level.java:1115) ~[?:?]
	at net.minecraft.world.level.block.FireBlock.trySpread(FireBlock.java:300) ~[?:?]
	at net.minecraft.world.level.block.FireBlock.tick(FireBlock.java:212) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1205) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1417) ~[?:?]
	at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:197) ~[?:?]
	at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:94) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:863) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1577) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: method must be annotated with @Query!
	at com.hakan.spinjection.database.executor.DatabaseExecutor.postCall(DatabaseExecutor.java:126) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.database.executor.DatabaseExecutor.preCall(DatabaseExecutor.java:112) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.utils.ProxyUtils.lambda$create$0(ProxyUtils.java:34) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at jdk.proxy4.$Proxy69.save(Unknown Source) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.testing.hibernatetestforspigot.listener.BreakBlockListener.onBlockBreak(BreakBlockListener.java:25) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	... 36 more
```

As a result, an annotation is needed even for standard methods, and this point was omitted for the sake of simplicity of the example?

**Comment by hakan-krgn** [comment]
Hello, "method must be annotated with @Query!" It comes from native database support and there is no save or delete method in native database support. Can you share your repository with me to check?

**Comment by thehuze** [comment]
I have uploaded all the code for you 
https://github.com/thehuze/hibernate-test-for-spigot/tree/master

**Comment by hakan-krgn** [comment]
Remove native dependency
https://github.com/thehuze/hibernate-test-for-spigot/blob/master/pom.xml#L153

**Comment by thehuze** [comment]
I removed the native dependency and tried to do exactly the same as in the example. The plugin does not start with an error

```
[10:09:26 INFO]: [spark] Enabling spark v1.10.55
[10:09:26 INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[10:09:26 INFO]: [spark] Starting background profiler...
[10:09:27 INFO]: [hibernate-test-for-spigot] Enabling hibernate-test-for-spigot v1.0-SNAPSHOT
[10:09:28 INFO]: [org.hibernate.Version] HHH000412: Hibernate ORM core version [WORKING]
[10:09:28 ERROR]: Error occurred while enabling hibernate-test-for-spigot v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: jakarta/persistence/Entity
	at com.hakan.spinjection.database.connection.DbConnection.buildFactory(DbConnection.java:246) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.database.connection.DbConnection.<init>(DbConnection.java:68) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.database.executor.DatabaseExecutor.execute(DatabaseExecutor.java:103) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.database.module.DatabaseModule.execute(DatabaseModule.java:62) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at com.hakan.spinjection.SpigotBootstrap.<init>(SpigotBootstrap.java:85) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.SpigotBootstrap.run(SpigotBootstrap.java:39) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.testing.hibernatetestforspigot.Hibernate_test_for_spigot.onEnable(Hibernate_test_for_spigot.java:12) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:658) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:569) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: jakarta.persistence.Entity
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 20 more
[10:09:28 INFO]: [hibernate-test-for-spigot] Disabling hibernate-test-for-spigot v1.0-SNAPSHOT
```

**Comment by hakan-krgn** [comment]
It's actually so clear, add jakarta persistence dependency to your plugin

**Comment by thehuze** [comment]
Added maven dep
```
 <!-- https://mvnrepository.com/artifact/jakarta.persistence/jakarta.persistence-api -->
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
            <version>3.1.0</version>
            <scope>compile</scope>
        </dependency>
```

Now it does not load data from the DbCredential instance
```
[10:27:56 INFO]: [spark] Starting background profiler...
[10:27:57 INFO]: [hibernate-test-for-spigot] Enabling hibernate-test-for-spigot v1.0-SNAPSHOT
[10:27:58 INFO]: [org.hibernate.Version] HHH000412: Hibernate ORM core version [WORKING]
[10:27:58 INFO]: [org.hibernate.annotations.common.Version] HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
[10:27:58 WARN]: [org.hibernate.orm.connections.pooling] HHH10001002: Using built-in connection pool (not intended for production use)
[10:27:58 INFO]: [org.hibernate.orm.connections.pooling] HHH10001005: Loaded JDBC driver class: com.mysql.cj.jdbc.Driver
[10:27:58 INFO]: [org.hibernate.orm.connections.pooling] HHH10001012: Connecting with JDBC URL [jdbc:mysql://localhost:3306]
[10:27:58 INFO]: [org.hibernate.orm.connections.pooling] HHH10001001: Connection properties: {password=****, autocommit=true, user=root}
[10:27:58 INFO]: [org.hibernate.orm.connections.pooling] HHH10001003: Autocommit mode: true
[10:27:58 INFO]: [org.hibernate.orm.connections.pooling] HHH10001115: Connection pool size: 20 (min=1)
[10:27:58 WARN]: [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] HHH000342: Could not obtain connection to query metadata
java.lang.IllegalStateException: Cannot get a connection as the driver manager is not properly initialized
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.getConnection(DriverManagerConnectionProviderImpl.java:214) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:214) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:109) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:107) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.convertSqlException(BasicConnectionCreator.java:108) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:41) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:57) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.addConnections(DriverManagerConnectionProviderImpl.java:448) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.<init>(DriverManagerConnectionProviderImpl.java:314) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.<init>(DriverManagerConnectionProviderImpl.java:290) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections$Builder.build(DriverManagerConnectionProviderImpl.java:492) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.buildPool(DriverManagerConnectionProviderImpl.java:99) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:74) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:107) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:179) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:107) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:181) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:411) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:80) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:707) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:746) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.database.connection.DbConnection.buildFactory(DbConnection.java:251) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.database.connection.DbConnection.<init>(DbConnection.java:68) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.database.executor.DatabaseExecutor.execute(DatabaseExecutor.java:103) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.database.module.DatabaseModule.execute(DatabaseModule.java:62) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at com.hakan.spinjection.SpigotBootstrap.<init>(SpigotBootstrap.java:85) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.SpigotBootstrap.run(SpigotBootstrap.java:39) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.testing.hibernatetestforspigot.Hibernate_test_for_spigot.onEnable(Hibernate_test_for_spigot.java:12) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:658) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:569) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:27:58 INFO]: [SQL dialect] HHH000400: Using dialect: org.hibernate.dialect.MySQL8Dialect
[10:27:58 WARN]: [org.hibernate.orm.deprecation] HHH90000025: MySQL8Dialect has been deprecated; use org.hibernate.dialect.MySQLDialect instead
[10:27:59 WARN]: [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] SQL Error: 0, SQLState: 08S01
[10:27:59 ERROR]: [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[10:27:59 ERROR]: Error occurred while enabling hibernate-test-for-spigot v1.0-SNAPSHOT (Is it up to date?)
org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:275) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:181) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:411) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:80) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:707) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:746) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.database.connection.DbConnection.buildFactory(DbConnection.java:251) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.database.connection.DbConnection.<init>(DbConnection.java:68) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.database.executor.DatabaseExecutor.execute(DatabaseExecutor.java:103) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.database.module.DatabaseModule.execute(DatabaseModule.java:62) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at com.hakan.spinjection.SpigotBootstrap.<init>(SpigotBootstrap.java:85) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at com.hakan.spinjection.SpigotBootstrap.run(SpigotBootstrap.java:39) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.testing.hibernatetestforspigot.Hibernate_test_for_spigot.onEnable(Hibernate_test_for_spigot.java:12) ~[hibernate-test-for-spigot-1.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:658) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:569) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by hakan-krgn** [comment]
Do you have an active mysql connection? If you have are you sure that username and password is correct?

**Comment by thehuze** [comment]
My configuration file config.yml contains the PostgreSQL driver. The database itself is deployed in docker and accepts connections.

```
db:
  url: jdbc:postgresql://localhost:5432/vlad
  driver: org.postgresql.Driver
  username: vlad
  password: vlad
```
![image](https://github.com/hakan-krgn/spigot-injection/assets/49346608/916810a7-5498-4783-97c8-f660ccc883f1)


Tried to replace hibernate8 with hibernate-core and i still have same error

**Comment by hakan-krgn** [comment]
Try to change your HibernateConfig with this
```java
    @Provide
    public DbCredential dbCredential(Config config) {
        return new DbCredential(
                config.getUrl(),
                "",
                config.getUsername(),
                config.getPassword()
        );
    }

    @Provide
    public DbProperties dbProperties() {
        DbProperties properties = new DbProperties();

        properties.set("hibernate.hbm2ddl.auto", "update");
        properties.set("hibernate.connection.autocommit", "true");
        properties.set("hibernate.dialect", "org.hibernate.dialect.PostgreSQLDialect");
        properties.set("hibernate.connection.driver_class", "org.postgresql.Driver");

        return properties;
    }
```

**Comment by thehuze** [comment]
Now it works as expected. Thank you for help!
